### ISSUE TITLE
group indicator

### ISSUE THREAD

**Issue by gitlerat** [vetelko/termbar#2]
Hi, is there a way to show the current group of cwm? I dont get it...

**Comment by gitlerat** [comment]
that would be realy cool... any updates on this?

**Comment by is73** [comment]
> that would be realy cool... any updates on this?

Sorry for the delay gitlerat

GROUP_ID=$(xprop -root 32c '\t$0' _NET_CURRENT_DESKTOP | cut -f 2)

**Comment by vetelko** [comment]
Sorry for the delay
GROUP_ID=$(xprop -root 32c '\t$0' _NET_CURRENT_DESKTOP | cut -f 2)
